### ISSUE TITLE
Unable to open file: vae.hdf5

### ISSUE THREAD

**Issue by asdcid** [kekegg/DLEPS#3]
Hi,
This package is very useful, but I got an error when i tried to run the testt sample:

```
~/devel/DLEPS/code/DLEPS$ python driv_DLEPS.py --input=../../data/Brief_Targetmol_natural_product_2719 --output=../../results/np2719_Browning.csv --upset=../../data/BROWNING_up --downset=../../data/BROWNING_down --reverse=False
Using TensorFlow backend.
WARNING:tensorflow:From /home/raymond/devel/miniconda3/envs/rdkit-env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "driv_DLEPS.py", line 69, in <module>
    main()
  File "driv_DLEPS.py", line 50, in main
    predictor = DLEPS(reverse=args.reverse, up_name=args.upset, down_name=args.downset)
  File "/data/raymond/devel/DLEPS/code/DLEPS/dleps_predictor.py", line 51, in __init__
    self.model.append(self._build_model())
  File "/data/raymond/devel/DLEPS/code/DLEPS/dleps_predictor.py", line 76, in _build_model
    grammar_model = molecule_vae.ZincGrammarModel(grammar_weights)
  File "/data/raymond/devel/DLEPS/code/DLEPS/molecule_vae.py", line 70, in __init__
    self.vae.load(self._productions, weights_file, max_length=self.MAX_LEN, latent_rep_size=latent_rep_size)
  File "/data/raymond/devel/DLEPS/code/DLEPS/models/model_zinc.py", line 140, in load
    self.create(charset, max_length = max_length, weights_file = weights_file, latent_rep_size = latent_rep_size)
  File "/data/raymond/devel/DLEPS/code/DLEPS/models/model_zinc.py", line 65, in create
    self.autoencoder.load_weights(weights_file)
  File "/home/raymond/devel/miniconda3/envs/rdkit-env/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/raymond/devel/miniconda3/envs/rdkit-env/lib/python3.6/site-packages/keras/engine/network.py", line 1221, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/home/raymond/devel/miniconda3/envs/rdkit-env/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/raymond/devel/miniconda3/envs/rdkit-env/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../../data/vae.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

There is no `vae.hdf5` file in the downloaded `data` folder. Do you have any idea about this?

Thanks,
Raymond

**Comment by bitcometz** [comment]
Could someone help with this problem？

**Comment by bitcometz** [comment]
the hdf5 file is mentioned here:
https://github.com/kekegg/DLEPS/issues/1

**Comment by asdcid** [comment]
Hi btcometz,

Thanks, I have downloaded it, but it complained with another missing h5 file: `denseweight.h5` now.

Cheers,
R

**Comment by bitcometz** [comment]
yes, I also meet with the problem !!!

**Comment by sailseem** [comment]
> Hi btcometz,
> 
> Thanks, I have downloaded it, but it complained with another missing h5 file: `denseweight.h5` now.
> 
> Cheers,
> R

Did you get it worked? Even though I downloaded the hdf5 files, I still cannot get the first Predict function work, the error still there, put it under data folder, right? I cannot believe that no one take care of this package.

**Comment by joey0214** [comment]
@asdcid @sailseem hi, guys, any lucky to make it run?

**Comment by asdcid** [comment]
> @asdcid @sailseem hi, guys, any lucky to make it run?

No, I gave up. Sorry.
